config/routes.rb
Rails.application.routes.draw do
  resources :appointments
  resources :vets
  resources :dogs
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/appointment.rb
class Appointment < ApplicationRecord
  belongs_to :vet
  belongs_to :dog
end

app/models/dog.rb
class Dog < ApplicationRecord
    has_many :appointments
    has_many :vets, through: :appointments

    validates :name, presence: true 
    validates :breed, presence: true 
end

app/models/vet.rb
class Vet < ApplicationRecord
    has_many :appointments
    has_many :dogs, through: :appointments

    validates :name, numericality: false 
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

end

app/controllers/appointments_controller.rb
class AppointmentsController < ApplicationController

    def index
        @appointments = Appointment.all
    end

    def show
        @appointment = Appointment.find(params[:id])
    end

    def new
        @appointment = Appointment.new
    end

    def create
        # @appointment = Appointment.create(vet_id: params[:appointment][:vet_id], dog_id: params[:appointment][:dog_id])
        @appointment = Appointment.create(appointment_params)
        redirect_to appointment_path(@appointment)
    end


    private

    def appointment_params
        params.require(:appointment).permit(:dog_id, :vet_id)
    end

end

app/controllers/dogs_controller.rb
class DogsController < ApplicationController
    skip_before_action :verify_authenticity_token

    def show
        @dog = Dog.find(params[:id])
    end

    def index
        @dogs = Dog.all 
    end

    def new
        @dog = Dog.new
    end

    def create
        @dog = Dog.new(dog_params)
        if @dog.valid?  
            @dog.save
            redirect_to dog_path(@dog)
        else
            render :new  
        end 
    end

    def edit 
        @dog = Dog.find(params[:id])
    end

    def update
        @dog = Dog.find(params[:id])

        if @dog.update(dog_params)
            redirect_to dog_path(@dog)
        else
            render :edit
        end 
    end

    def destroy
        @dog = Dog.find(params[:id])
        @appointments = Appointment.all.select {|app| app.dog_id == @dog.id}

        @appointments.each do |app|
            app.destroy
        end 
        
        @dog.destroy
        redirect_to dogs_path
    end

    private

    def dog_params 
        params.require(:dog).permit(:name, :breed)
    end

end

app/controllers/vets_controller.rb
class VetsController < ApplicationController
    skip_before_action :verify_authenticity_token
    def show
        @vet = Vet.find(params[:id])
    end

    def index
        @vets = Vet.all
    end

    def new
        @vet = Vet.new 
    end
    
    def create
        @vet = Vet.create(vet_params)
        #TODO validations logic 
        redirect_to vet_path(@vet)
    end

    def edit
        @vet = Vet.find(params[:id])
    end

    def update
        @vet = Vet.find(params[:id])
        @vet.update(vet_params)
        redirect_to vet_path(@vet)
    end

    def destroy
        @vet = Vet.find(params[:id])
        @vet.destroy
    end

    private 

    def vet_params
        params.require(:vet).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/appointments_helper.rb
module AppointmentsHelper
end

app/helpers/dogs_helper.rb
module DogsHelper
end

app/helpers/names_helper.rb
module NamesHelper
end

app/helpers/vets_helper.rb
module VetsHelper
end

app/views/appointments/index.html.erb
<h1>EVERY APPOINTMENT</h1>
<%= link_to('ADD APPOINTMENT', '/appointments/new') %><br>
<hr>
<% @appointments.each do |app| %>
<%= link_to(app.name, appointment_path(app))  %> </br>
<% end  %>

app/views/appointments/new.html.erb
<%= form_for @appointment do |f| %>

    <%= f.label :dog_id %>
    <%= f.collection_select :dog_id, Dog.all, :id, :name %>
    <br>
    <%= f.label :vet_id %>
    <%= f.collection_select :vet_id, Vet.all, :id, :name %>
    <%= f.submit %>

<% end %>

app/views/appointments/show.html.erb
<h2>the dog <%= @appointment.dog.name %></h2> <br>
<h2>the vet <%= @appointment.vet.name %></h2>

app/views/dogs/edit.html.erb
<% if @dog.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= pluralize(@dog.errors.count, "error") %>
      prohibited this dog from being saved:
    </h2>
 
    <ul>
    <% @dog.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>


<%= form_for @dog  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :breed %>
  <%= f.text_field :breed %>

  
  <br />

  <%= f.submit %>
<% end %>

app/views/dogs/index.html.erb
<h1>EVERY DOG</h1>

<%= button_to('ADD DOG', new_dog_path, method: :get) %> <br> 
<hr>


<% @dogs.each do |dog| %>
<%= link_to(dog.name, dog_path(dog.id))  %> </br>
<% end  %>

app/views/dogs/new.html.erb
  
<%= form_for @dog  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>

  <%= f.label :breed %>
  <%= f.text_field :breed %>

  
  <br />

  <%= f.submit %>
<% end %>

app/views/dogs/show.html.erb
<h1>MY COOL DOG</h1>
<h2>his name is <%= @dog.name %> </h2>
<h2>his breed is <%= @dog.breed %> </h2>

<%= button_to "Back", dogs_path, method: :get %>
<%= button_to "Delete Dog :(", dog_path(@dog), method: :delete %>
<%= button_to "Edit Dog :)", edit_dog_path(@dog), method: :get %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Dogtime</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/vets/edit.html.erb
  
<%= form_for @vet  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>


  <br />

  <%= f.submit %>
<% end %>

app/views/vets/index.html.erb
<h1>ALL MY VETS</h1>

<%= button_to('NEW VET', new_vet_path, method: :get) %> <br>
<hr>
<% @vets.each do |vet| %>
<%= link_to(vet.name, vet_path(vet)) %> <br>
<% end  %>

app/views/vets/new.html.erb
  
<%= form_for @vet  do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>


  <br />

  <%= f.submit %>
<% end %>

app/views/vets/show.html.erb
<h1>MY VET IS <%= @vet.name %> </h1>
<%= button_to 'BACK', vets_path, method: :get %>
<%= button_to 'EDIT VET', edit_vet_path(@vet), method: :get %>
<%= button_to 'DELETE VET', vets_path, method: :destroy %>